Extensions/XEP-0077/XMPPRegistration.m
Based on the discussion [here](https://github.com/robbiehanson/XMPPFramework/commit/1cea8429b3c125c7af0187e26cdfb052159f9b29?diff=unified), using `childCount == 0` on [this line](https://github.com/robbiehanson/XMPPFramework/blob/master/Extensions/XEP-0077/XMPPRegistration.m#L165) and [this line](https://github.com/robbiehanson/XMPPFramework/blob/master/Extensions/XEP-0077/XMPPRegistration.m#L206) is a poor means of validation, since the code above is already checking for errors.
I also removed an `NSLog` statement.
=> Updated XEP-0077 to no longer use childCount == 0 as validation

Extensions/XEP-0060/XMPPPubSub.h, Extensions/XEP-0060/XMPPPubSub.m
Implemented "6.5 Retrieve Items from a Node" from the XMPP PubSub Extension Specification (XEP-0060).
Added methods for retrieving items from a node and appropriate delegate methods.
Renamed existing retrieveDict dictionary to retrieveSubsDict and added a new dictionary retrieveItemsDict.
=> Implemented "6.5 Retrieve Items from a Node" from XEP-0060

Authentication/Digest-MD5/XMPPDigestMD5Authentication.m, Authentication/Plain/XMPPPlainAuthentication.h, Authentication/Plain/XMPPPlainAuthentication.m, Authentication/SCRAM-SHA-1/XMPPSCRAMSHA1Authentication.m, Authentication/XMPPSASLAuthentication.h
The username used for authentication may not be the same as the user part of a JID (see https://tools.ietf.org/html/rfc6120#section-6.3.7). This PR allows a different username to be used (if needed) while still defaulting to use the user part of the JID.
=> Allow a different username to be used for authentication

Extensions/XEP-0147/XMPPURI.h, Extensions/XEP-0147/XMPPURI.m, Xcode/Testing2/Podfile, Xcode/Testing2/Podfile.lock, Xcode/Testing2/XMPPFrameworkTests/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing2/XMPPFrameworkTests/XMPPFrameworkTestsTests/XMPPURITests.m
This adds basic support for generating and parsing XMPP URIs defined in [XEP-0147](http://xmpp.org/extensions/xep-0147.html) and [RFC 5122](http://tools.ietf.org/html/rfc5122). I also added a few tests in the XCTest "Testing2" area.
=> Support for XMPP URIs (XEP-0147 / RFC 5122)

Extensions/XEP-0045/CoreDataStorage/XMPPRoomCoreDataStorage.m
XMPPJID * roomJID is used in this method for predicate building. Due to this method returns nil. Method returns what is expected if NSString * roomJID.bare is used.
=> Fixed bug when mostRecentMessageTimestampForRoom returns nil

Extensions/XEP-0066/XMPPMessage+XEP_0066.m
`jabber:iq:oob` used with `XMPPIQ`, but `jabber:x:oob` should be used with `XMPPMessage`
=> fix XEP-0066 message namespace

Extensions/XEP-0184/XMPPMessage+XEP_0184.m
Hi
XEP-0184 is working fine while online. But If the message is delivered while the sender is offline the sender can't be notified when he/she is online again. Then I figured out the "type" attribute is missing from the receipt response.
By the way I am using Openfire as XMPP server.
=> XEP-0184 - Message delivery receipts while offline

Core/XMPPLogging.h, XMPPFramework.podspec
In CocoaLumberjack 2.0 has a parameter for a 'potential tag'. For now I've set this to nil. Is there something we should pass otherwise?
=> Updated to CocoaLumberjack 2.0

Extensions/XEP-0334/XMPPMessage+XEP_0334.h, Extensions/XEP-0334/XMPPMessage+XEP_0334.m, XMPPFramework.podspec, Xcode/Testing-pod/Podfile.lock, Xcode/Testing-pod/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-pod/XMPPFrameworkTests.xcodeproj/xcshareddata/xcschemes/XMPPFrameworkTests.xcscheme, Xcode/Testing-pod/XMPPFrameworkTests/XMPPStorageHintTests.m
http://xmpp.org/extensions/xep-0334.html
> This specification aims to solve the following common problems, and allow a sender to hint to the recipient:
Whether to store a message (e.g. for archival or as an 'offline message').
Whether to copy a message to other resources.
Whether to store a message that would not have been stored under normal condition
=> XEP-0334: Message Processing Hints

Extensions/XEP-0054/CoreDataStorage/XMPPvCardCoreDataStorage.m
clearing local vCard -> cache is out of date -> lastUpdate = distantPast
lastUpdate is for local cache update and is considered when fetching a
new vCard.
If we set it to the date of *clearing* the cache new fetch will not be
made for at least 10 seconds (kXMPPvCardTempNetworkFetchTimeout).
So we should set it to the distant past, signaling that our local cache
is out of date. New fetches will go through (shouldFetchvCardTempForJID
returns YES)
=> Fix avatar clearing vcard, no new fetches for 10 seconds

Extensions/XEP-0054/XMPPvCardTempModule.h, Extensions/XEP-0054/XMPPvCardTempModule.m, Xcode/Testing-pod/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-pod/XMPPFrameworkTests.xcworkspace/xcshareddata/XMPPFrameworkTests.xcscmblueprint, Xcode/Testing-pod/XMPPFrameworkTests/XMPPMockStream.h, Xcode/Testing-pod/XMPPFrameworkTests/XMPPMockStream.m, Xcode/Testing-pod/XMPPFrameworkTests/XMPPvCardTests.m
I had a need for a delegate callback for failure to fetch vCard. In the process I added test coverage to XMPPvCardTempModule using the new XMPPMockStream class. I also modified the XMPPMockStream class to act more like a regular stream to better support multicast delegate / modules.
When testing against Prosody I noticed they don't conform to the spec, so.. yeah.
=> Added vCard failure delegate and more tests

Extensions/XMPPMUCLight/CoreDataStorage/XMPPRoomLight.xcdatamodel/contents, Extensions/XMPPMUCLight/CoreDataStorage/XMPPRoomLightCoreDataStorage.m, Extensions/XMPPMUCLight/XMPPRoomLight.h, Extensions/XMPPMUCLight/XMPPRoomLight.m, Xcode/Testing-Shared/XMPPRoomLightTests.m
I've been using XMPPRoom heavily lately and I found a couple of simple bugs this fixes them:
- Wrong name in the class value of the entity in XMPPRoomLight.xcdatamodel
- When sending a message to a MUC light room that same message was stored when received
- Added two different values for the Version to XMPPRoom one to use when fetching members and one to use when fetching the config, and a method to flush the version. If the same was used I couldn't get the list of members after getting the configuration.
- When fetching the list of members if no members where in the IQ received it was returning an nil and sending that nil to a delegate method that accepted nonnulls.
=> Andres.bugs xmpp room light

Extensions/XEP-0115/XMPPCapabilities.h, Extensions/XEP-0115/XMPPCapabilities.m
Been seeing a few of these crashes in production. In theory this will fix it..
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[XMPPJID cancel]: unrecognized selector sent to instance 0x149423730'
Last Exception Backtrace:
0   CoreFoundation                       0x0000000180f7adb0 __exceptionPreprocess + 124
1   libobjc.A.dylib                      0x00000001805dff80 objc_exception_throw + 52
2   CoreFoundation                       0x0000000180f81c4c -[NSObject(NSObject) doesNotRecognizeSelector:] + 208
3   CoreFoundation                       0x0000000180f7ebec ___forwarding___ + 868
4   CoreFoundation                       0x0000000180e7cc5c _CF_forwarding_prep_0 + 88
5   XMPPFramework …
=> Fix crash in XMPPCapabilities dealloc

Extensions/XEP-0045/XMPPRoom.h, Extensions/XEP-0045/XMPPRoom.m
After a `XMPPRoom` did receive subject change, the event is delegated through `multiCastDelegate` so a `XMPPRoomDelegate` can be notified about change and perform actions (e.g. for UI changes).
=> delegate subject change to multicastDelegate

Core/XMPPStream.h, Core/XMPPStream.m
You should make sure you're using the latest release of CocoaAsyncSocket (7.5.1 or higher) if your IPv6 network is unreliable so the IPv4 fallback works.
=> Prefer IPv6 over IPv4 by default, partially fixes #718

Extensions/XEP-0045/XMPPRoom.m
Fixes bug where server answers with „invalid from“ error on attempt to change subject.
Set from to myJID instead of myRoomJID in subjet change message.
See example in http://xmpp.org/extensions/xep-0045.html#subject-mod.
I'm not sure if other servers handle it different but ejabberd just closes the connection if the roomjid of the user is used. However, the XEP description means usage of the "normal" jid and this PR will fix that.
=> Fix for subject change error "invalid from"

Extensions/ProcessOne/XMPPProcessOne.m, Extensions/XEP-0357/XMPPIQ+XEP_0357.m, Xcode/Testing-Shared/XMPPPushTests.swift
ejabberd 16.09+ rejects stanzas that don't match the specs, so enabling `xmpp:push` feature from ChatSecure does not work.
=> "id" attribute is required for IQ stanzas

Extensions/XEP-0060/XMPPPubSub.h, Extensions/XEP-0060/XMPPPubSub.m, Xcode/Testing-Shared/XMPPPubSubTests.m, Xcode/Testing-iOS/XMPPFrameworkTests.xcodeproj/project.pbxproj
This reverts #249 and introduces custom delegate-driven incoming message filtering. Fixes #918.
=> Custom filtering of incoming PEP event messages

Extensions/XMPPMUCLight/CoreDataStorage/XMPPRoomLightCoreDataStorage.m
Storing room message JIDs of the form `room@muclight.domain/user@user.domain/user.resource` causes them to be misidentified as incoming when the sender gets assigned a different resource next time they connect.
=> Ignore user’s resource when storing MUC Light messages

Core/XMPPStream.h, Core/XMPPStream.m, Extensions/Reconnect/XMPPReconnect.m
Fixes #935.
With this change, XMPPReconnect will abort any in-progress connection attempt and initiate a new one on every timer/reachability callback.
=> Force XMPPReconnect connection attempts

Extensions/XEP-0313/XMPPMessageArchiveManagement.h, Extensions/XEP-0313/XMPPMessageArchiveManagement.m, Xcode/Testing-Shared/XMPPMessageArchiveManagementTests.m
In the current implementation, MAM module ceases any activity after retrieving the first page of results. It is the caller's responsibility to issue a query for the next page. This is quite inconvenient as it forces them to keep or recreate the original query for subsequent pages.
Additionally, the delegate API does not explicitly indicate that the last page has been fetched: `xmppMessageArchiveManagement:didFinishReceivingMessagesWithSet:` only delivers the result set element while this information is contained higher in the tree, in the `fin` element.
This PR adds a new property to the module, `resultAutomaticPagingPageSize`. Once set to a non-zero value, it will cause queries for further pages to be issued automatically. Each page query will then result in either …
=> Add an option to automatically page through MAM fetch results

Extensions/XMPPMUCLight/XMPPRoomLight.h, Extensions/XMPPMUCLight/XMPPRoomLight.m, Xcode/Testing-Shared/XMPPRoomLightTests.m
Fixes #942.
This introduces the `knownMembersList` property which holds the most recently fetched occupants list. This is akin to how the existing configuration-derived properties work (`roomname`, `subject`).
The PR also changes `xmppRoomLight:didFetchMembersList:` callback to return the full result IQ. The rationale is as follows:
* Returning only an empty array after a version-matched fetch appears confusing
* All the other IQ response callbacks return full result stanzas
=> MUC Light members list in-module storage

Core/XMPPIQ.m, Extensions/Roster/XMPPRoster.m
This pull request addresses issue #908, fixing all the instances I found where the "id" attribute was missing from IQ stanzas and thereby fixing compatibility with ejabberd version 17.01
=> Fix missing "id" attribute in some IQ stanzas

Extensions/Reconnect/XMPPReconnect.m
Fixes #946.
With this change, forced reconnect retry runs in the following properly sequenced steps:
1. A forced retry flag is raised when appropriate before triggering a reconnect attempt (reachability changed or a reconnect timer fired).
2. When a reconnect attempt is triggered while another one is still in progress, the forced retry flag triggers aborting the latter.
3. After the in progress attempt is completely aborted, the retry is started.
=> XMPPReconnect forced retries fix

Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchivingCoreDataStorage.h, Extensions/XEP-0136/CoreDataStorage/XMPPMessageArchivingCoreDataStorage.m
The current implementation will not store a message unless it has nonempty body. This presents issues for certain kinds of messages, e.g. an out-of-band message (0066) containing a link but no body will never get stored.
This PR introduces XPath-based message content testing; the default configuration ensures that the behavior is not changed, i.e. only the `body` element is tested.
=> More flexible XMPPMessageArchivingCoreDataStorage message content filter

Core/XMPPStream.m, Utilities/XMPPSRVResolver.h, Utilities/XMPPSRVResolver.m
This change is not API compatible if you were using XMPPSRVResolver outside of XMPPStream.
=> Fix crash in XMPPSRVResolver

Extensions/XEP-0313/XMPPRoomLightCoreDataStorage+XEP_0313.m, Extensions/XMPPMUCLight/XMPPRoomLight.h, Extensions/XMPPMUCLight/XMPPRoomLight.m, Xcode/Testing-Shared/XMPPRoomLightCoreDataStorageTests.m
In order to correctly implement last message correction in the context of group messaging, one needs to keep room affiliation change history. This is needed to prevent post-rejoin corrections, as described in the [security considerations](https://xmpp.org/extensions/xep-0308.html#security) section of the XEP.
This pull request adds a MUC Light room module flag that controls whether affiliation change messages are directed to the storage (disabled by default).
=> Allow storing MUC Light affiliation change messages

Extensions/XEP-0136/XMPPMessageArchiving.m
The request to get the `archive` from `XMPPMessageArchiving` class missed the id.
Without this `id` the server answers with ```Missing required 'id' attribute```.
Sample response without it:
```
<iq xmlns="jabber:client" type="error"><error type="modify"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Missing required 'id' attribute</text></error></iq>
```
=> Add missing id on get archive xml request

Extensions/XEP-0184/XMPPMessage+XEP_0184.m
Fix:
- Added type
- Bare JID (without the resource) instead of the full JID string
=> XEP-0184 Fix For Group Chat

Core/XMPPFramework.h, Extensions/XEP-0066/XMPPOutOfBandResourceMessaging.h, Extensions/XEP-0066/XMPPOutOfBandResourceMessaging.m, XMPPFramework.xcodeproj/project.pbxproj, Xcode/Testing-Carthage/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-Shared/XMPPOutOfBandResourceMessagingTests.m, Xcode/Testing-iOS/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-macOS/XMPPFrameworkTests.xcodeproj/project.pbxproj
This pull request implements a module managing XEP-0066 auxiliary resource URIs embedded in messages, one of the modules described in the "Currently supported XMPP extensions" section in #993.
Storage helpers implementation is not yet included here, as it depends on both #996 and #997.
=> Out of band data URI message handling module

Extensions/XMPPMUCLight/XMPPMUCLight.h, Extensions/XMPPMUCLight/XMPPMUCLight.m, Xcode/Testing-Shared/XMPPMUCLightTests.m
This pull requests fixes the following issues in MUC Light `-xmppMUCLight:changedAffiliation:roomJID:` callback: 
* The callback was only invoked once per incoming affiliation change message even if the server reported changes for several occupants.
* The callback didn't include the JID of the occupant whose affiliation changed
The above fix is a prerequisite to introduce the last message correction handling module, one of the modules mentioned in the "Currently supported XMPP extensions" section in #993.
Technically, this pull request breaks `XMPPMUCLightDelegate` API. There are some good reasons to do so though:
* MUC Light may still be considered as having "semi-experimental" status
* The callback in its old form could misguide application developers leading to bugs where some …
=> Fix MUC Light affiliation change handling

Extensions/XMPPMUCLight/XMPPRoomLight.h, Extensions/XMPPMUCLight/XMPPRoomLight.m, Xcode/Testing-Shared/XMPPRoomLightCoreDataStorageTests.m
This pull request enables MUC Light module to report group chat messages without body (e.g. only containing Out-of-Band URI) to its storage. This is a prerequisite for making MUC Light compatible with XMPPMessageCoreDataStorage as described in #993.
The added flag is not documented, but it should be self-explanatory.
=> MUC Light empty message handling

Core/XMPPFramework.h, Extensions/OneToOneChat/XMPPOneToOneChat.h, Extensions/OneToOneChat/XMPPOneToOneChat.m, XMPPFramework.xcodeproj/project.pbxproj, Xcode/Testing-Carthage/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-Shared/XMPPOneToOneChatTests.m, Xcode/Testing-iOS/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-macOS/XMPPFrameworkTests.xcodeproj/project.pbxproj
This pull request implements private chat handling module, one of the modules described in the "Currently supported XMPP extensions" section in #993.
Storage helpers implementation is not yet included here, as it depends on both #996 and #997.
=> Basic one to one chat module implementation

Core/XMPPFramework.h, Extensions/XEP-0203/NSXMLElement+XEP_0203.h, Extensions/XEP-0203/NSXMLElement+XEP_0203.m, Extensions/XEP-0203/XMPPDelayedDelivery.h, Extensions/XEP-0203/XMPPDelayedDelivery.m, XMPPFramework.xcodeproj/project.pbxproj, Xcode/Testing-Carthage/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-Shared/XMPPDelayedDeliveryTests.m, Xcode/Testing-iOS/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-macOS/XMPPFrameworkTests.xcodeproj/project.pbxproj
This pull request implements XEP-0203 delayed delivery handling module, one of the modules described in the "Currently supported XMPP extensions" section in #993.
Storage helpers implementation is not yet included here, as it depends on both #996 and #997.
=> Delayed delivery module

Core/XMPPFramework.h, Extensions/XEP-0198/Managed Messaging/XMPPManagedMessaging.h, Extensions/XEP-0198/Managed Messaging/XMPPManagedMessaging.m, XMPPFramework.xcodeproj/project.pbxproj, Xcode/Testing-Carthage/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-Shared/XMPPManagedMessagingTests.m, Xcode/Testing-iOS/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-macOS/XMPPFrameworkTests.xcodeproj/project.pbxproj
This pull request implements a module handling outgoing message XEP-0198 acknowledgement statuses, one of the modules described in the "Currently supported XMPP extensions" section in #993.
Storage helpers implementation is not yet included here, as it depends on both #996 and #997.
=> XMPPManagedMessaging module

Extensions/XEP-0184/XMPPMessageDeliveryReceipts.h, Extensions/XEP-0184/XMPPMessageDeliveryReceipts.m, Xcode/Testing-Carthage/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-Shared/XMPPMessageDeliveryReceiptsTests.m, Xcode/Testing-iOS/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-macOS/XMPPFrameworkTests.xcodeproj/project.pbxproj
This pull request implements XEP-0184 receipt response processing. It is intended to be followed up by the XMPPMessageCoreDataStorage helper implementation pull request once #996 and #997 are merged.
=> Receipt response processing in XMPPMessageDeliveryReceipts

XMPPFramework.xcodeproj/project.pbxproj
Changed XMPPFrameworkSwift target's bundle identifiers to `org.robbiehanson.XMPPFrameworkSwift`. 
The issue is that XMPPFrameworkSwift targets have a dependency on XMPPFramework target. In this case, you have to add both frameworks to the project. Eventually, a device build fails on code signing - there are 2 dependencies with similar bundle ids `org.robbiehanson.XMPPFramework`.
=> XMPPFrameworkSwift target's bundle identifiers

Extensions/XEP-0198/XMPPStreamManagement.h
The makes all uses of `lastDisconnect` within `XMPPStreamManagementStorage ` nullable. This is how `lastDisconnect` is treated by `XMPPStreamManagementMemoryStorage`, and there are cases where `lastDisconnect` is nil when passed to the delegate (if a disconnect has never occurred). This causes a crash in Swift when the nil is unwrapped.
=> Fixes #1073. Correct nullability for lastDisconnect

Extensions/XEP-0054/XMPPvCardTemp.h, Extensions/XEP-0054/XMPPvCardTemp.m, Extensions/XEP-0054/XMPPvCardTempEmail.m, Extensions/XEP-0054/XMPPvCardTempTel.m, Xcode/Testing-Swift/XMPPvCardTempTests.swift, Xcode/Testing-iOS/XMPPFrameworkTests.xcodeproj/project.pbxproj, Xcode/Testing-macOS/XMPPFrameworkTests.xcodeproj/project.pbxproj
Fixes #1050 and #1118.
Setter methods in `XMPPcVardTempEmail` and `XMPPcVardTempTel` had typing mistakes. Must have been happened sometime during 3.7 to 4.0 transition. 
These types do not allow adding properties, that's why the allocated size is compared to the size of `NSXMLElement` in `initialize`. 
```
+ (void)initialize {
// .....
size_t superSize = class_getInstanceSize([NSXMLElement class]);
size_t ourSize   = class_getInstanceSize([XMPPvCardTempEmail class]);
if (superSize != ourSize)
{
XMPPLogError(@"Adding instance variables to XMPPvCardTempEmail is not currently supported!");
[DDLog flushLog];
exit(15);
}
}
```
Every added property has to have matching get and set overwrites, otherwise ObjC will allocate memory for the property and the size check will fail.
The linked issue …
=> Fix crashes in XMPPvCardTempEmail and XMPPvCardTempTel initialize
